// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1iYJKaHpvkJxOJ9FdrDuAsHaXkL1jK0Q',
    appId: '1:531413877779:web:79e8c4be0828402f3aebe6',
    messagingSenderId: '531413877779',
    projectId: 'fcmmessaging-a910a',
    authDomain: 'fcmmessaging-a910a.firebaseapp.com',
    storageBucket: 'fcmmessaging-a910a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVG7o2guD8xseIy5H83sjQgmoMY9nB6U',
    appId: '1:531413877779:android:01629a478397cca33aebe6',
    messagingSenderId: '531413877779',
    projectId: 'fcmmessaging-a910a',
    storageBucket: 'fcmmessaging-a910a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60okdbnUG_FVps0D-ayJcnOIHMLTSxbQ',
    appId: '1:531413877779:ios:514a2d26808710563aebe6',
    messagingSenderId: '531413877779',
    projectId: 'fcmmessaging-a910a',
    storageBucket: 'fcmmessaging-a910a.appspot.com',
    iosBundleId: 'com.example.fcmMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60okdbnUG_FVps0D-ayJcnOIHMLTSxbQ',
    appId: '1:531413877779:ios:514a2d26808710563aebe6',
    messagingSenderId: '531413877779',
    projectId: 'fcmmessaging-a910a',
    storageBucket: 'fcmmessaging-a910a.appspot.com',
    iosBundleId: 'com.example.fcmMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1iYJKaHpvkJxOJ9FdrDuAsHaXkL1jK0Q',
    appId: '1:531413877779:web:a9bbded5a7f10fe23aebe6',
    messagingSenderId: '531413877779',
    projectId: 'fcmmessaging-a910a',
    authDomain: 'fcmmessaging-a910a.firebaseapp.com',
    storageBucket: 'fcmmessaging-a910a.appspot.com',
  );
}
